/**
 * Environmental constants exposed to the UI.
 * Values delegate to the simulation's source of truth.
 */

import {
  RECOMMENDED_AIR_CHANGES_PER_HOUR,
  BASE_DEHUMIDIFICATION_LOAD_KG_PER_M2_HOUR,
  BASE_CO2_INJECTION_PPM_PER_TICK_PER_M2,
  AMBIENT_TEMPERATURE_C,
  AMBIENT_RELATIVE_HUMIDITY,
  AMBIENT_CO2_PPM,
  TEMPERATURE_NORMALIZATION_FACTOR,
  HUMIDITY_NORMALIZATION_FACTOR,
  CO2_NORMALIZATION_FACTOR,
  LAMP_HEAT_GAIN_K_PER_KW_TICK,
  COOLING_CAPACITY_EFFECT_K_PER_KW_TICK,
  DEHUMIDIFIER_HEAT_GAIN_K_PER_KW_TICK,
  PLANT_TRANSPIRATION_RH_PER_PLANT,
  PLANT_CO2_CONSUMPTION_PPM_PER_PLANT,
  AIR_DENSITY_KG_PER_M3,
} from '../../../game/constants/env';

export {
  RECOMMENDED_AIR_CHANGES_PER_HOUR,
  BASE_DEHUMIDIFICATION_LOAD_KG_PER_M2_HOUR,
  BASE_CO2_INJECTION_PPM_PER_TICK_PER_M2,
  AMBIENT_TEMPERATURE_C,
  AMBIENT_RELATIVE_HUMIDITY,
  AMBIENT_CO2_PPM,
  TEMPERATURE_NORMALIZATION_FACTOR,
  HUMIDITY_NORMALIZATION_FACTOR,
  CO2_NORMALIZATION_FACTOR,
  LAMP_HEAT_GAIN_K_PER_KW_TICK,
  COOLING_CAPACITY_EFFECT_K_PER_KW_TICK,
  DEHUMIDIFIER_HEAT_GAIN_K_PER_KW_TICK,
  PLANT_TRANSPIRATION_RH_PER_PLANT,
  PLANT_CO2_CONSUMPTION_PPM_PER_PLANT,
  AIR_DENSITY_KG_PER_M3,
};

// Legacy aliases maintained for backward compatibility with existing UI imports.
export const RECOMMENDED_ACH = RECOMMENDED_AIR_CHANGES_PER_HOUR;
export const BASE_DEHUMIDIFICATION_LOAD_PER_M2_PER_H = BASE_DEHUMIDIFICATION_LOAD_KG_PER_M2_HOUR;
export const AMBIENT_TEMP_C = AMBIENT_TEMPERATURE_C;
export const AMBIENT_HUMIDITY_RH = AMBIENT_RELATIVE_HUMIDITY;
export const LAMP_HEAT_FACTOR = LAMP_HEAT_GAIN_K_PER_KW_TICK;
export const COOLING_CAPACITY_FACTOR = COOLING_CAPACITY_EFFECT_K_PER_KW_TICK;
export const DEHUMIDIFIER_HEAT_FACTOR = DEHUMIDIFIER_HEAT_GAIN_K_PER_KW_TICK;
